### PR TITLE
use self refs

### LINKED ISSUE #134: Breakpoints don't get hit (possibly if imported with relative paths instead of `package:`)
1. Clone https://github.com/Dart-Code/analysis-server-typescript-generator at revision 514fd331c984a3808e3cf9a6cdcea7e1f4a66e21
1. Put a breakpoint on first line of `main` and another on first line of `ApiSpec.buildDefinitions`
1. Press `F5`; first breakpoint is hit
1. Press `F5` again; program runs to completion without hitting second breakpoint

### PR DESCRIPTION
**Pull request by devoncarew**
- use self-refs in bin/main.dart (likely fix https://github.com/Dart-Code/Dart-Code/issues/134)

### CODE REVIEW

**Comment by devoncarew** [comment]
This will probably fix that breakpoint issue; we were likely setting a package: url for the breakpoint, but the VM was executing it as a file one.

**Comment by DanTup** [comment]
After I shut down it crossed my mind this might be the cause. I actually had it this way, but it kinda bugged me having to duplicate the name in case I changed it in pubspec!

If this is the cause, I don't think it's a great user experience - it seems likely users could import either way (especially if in the same file, `import 'mything.dart';` is much better than `import 'package:my_package/mything.dart';`). I wonder if there's anything we can do to make this tolerate either.

I'll add notes to the other issue and keep it open for now for investigation.

**Comment by devoncarew** [comment]
Yup, for every user breakpoint, you could set two vm breakpoints (one using the file path and one using a package: path, if one is applicable).

Note though that it's a very strong convention to use self-references to reach into the `lib/` dir (and really enforced through different parts of the toolchain). Generally:
- within a folder (lib/, bin/ test/ ...), you use relative path references
- from another folder referencing code in lib/, you use self-refs
- it's generally not done to reference between two top-level, non-lib/, folders (from test/ to bin/ say)

**Comment by DanTup** [comment]
Adding responses in https://github.com/Dart-Code/Dart-Code/issues/134

**Pull request merged**
